### ISSUE TITLE
I can't get all contacts

### ISSUE THREAD

**Issue by Pahanuch** [UlrichRaab/rx-contacts#2] opened 2017-03-20 16:30 UTC
Thanks. Very good solution. But Why I don't get all contacts ? Some contacts skips

**Comment by UlrichRaab** [comment] 2017-03-21 09:01
Hello, can you provide an example of a contact that you do not get? It also would be nice to know what device and Android version you are using.

**Comment by Pahanuch** [comment] 2017-03-21 09:34
Samsung Galaxy J3 
Android 5.1.1

Any contacts. For example +7 926 987 65 43 (without spaces). But If I add more then one phone number, problem is gone. But first number always skips. So for example: I created contact (Maria). And Added 3 phone numbers (555 555 555, 666 666 666, 777 777 777). **Last couple** will be is available, **first** - skips.

**Comment by Pahanuch** [comment] 2017-03-21 12:51
I'm sorry. But when you can fix it ?

**Comment by UlrichRaab** [comment] 2017-03-21 17:48
I need to get a samsung device to be able to test. I tried it with my Nexus 5 and i dont have the issue. I already called a fried who owns a old samsung device and he will send it to me this week so that i can start fixing this.

**Comment by Pahanuch** [comment] 2017-03-23 17:02
I think the problem is not in device. I tested it on Emulator (Android 6.+).

**Comment by pnickv** [comment] 2017-03-30 11:12
I see the same issue

**Comment by pnickv** [comment] 2017-03-30 17:28
it looks like the issue is for emulators only

**Comment by Pahanuch** [comment] 2017-03-30 17:29
I get this issue on real device too

**Comment by UlrichRaab** [comment] 2017-03-31 07:16
I could reproduce the issue in a Samsung Device and will try to fix it asap. I hope i can Start working on it on sunday.

**Comment by Waterbyte** [comment] 2017-12-21 17:13
Under private void fetch (Subscriber<? super Contact> subscriber) {....} in RxContacts.java, Please add 
mapPhoneNumber(cursor,contact,idxData1) even if contact isn't present to resolve this issue. In your condition, you are adding Phone number and Email only if contact details are present before. That's why first one is always skipped.

**Comment by UlrichRaab** [comment] 2017-12-21 18:47
@Waterbyte Your bugfix looks good. I could test it on a Nexus 5X and want to test it on some other devices. I will do this tomorrow. I pushed the change to the dev branch in case you want to test by yourself.

Thank you

**Comment by UlrichRaab** [comment] 2017-12-22 09:49
I could test it on a Samsung Galaxy S8 and a HTC 10. It looks like the bugfix is working. I will publish the new version today.

**Comment by UlrichRaab** [comment] 2017-12-22 10:00
I have published the new version of RxContacts (1.1.3) and will close this issue.

**Closed as completed by UlrichRaab** 2017-12-22 10:00 UTC
Labels: bug

**Comment by Waterbyte** [comment] 2017-12-22 10:17
@UlrichRaab Nice, Thanks for the Library.
